version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:23.0.7
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: 
      - start-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - keycloak-net

volumes:
  keycloak_data:
    name: keycloak_data

networks:
  keycloak-net:
    name: keycloak-net
