/**
 * Keycloak Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './user-dto.model';


export interface ApiResponseUserDto { 
    success: boolean;
    data?: UserDto;
    error?: string;
}

