/**
 * Keycloak Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupDto } from './group-dto.model';


export interface ApiResponseGroupDto { 
    success: boolean;
    data?: GroupDto;
    error?: string;
}

