/**
 * Keycloak Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiResponseMapStringObject { 
    success: boolean;
    data?: { [key: string]: object | undefined; };
    error?: string;
}

