/**
 * Keycloak Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDto } from './role-dto.model';


export interface ApiResponseListRoleDto { 
    success: boolean;
    data?: Array<RoleDto>;
    error?: string;
}

