/**
 * Keycloak Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthConfigDto } from './authConfigDto';


export interface ApiResponseAuthConfigDto { 
    success: boolean;
    data?: AuthConfigDto;
    error?: string;
}

