/**
 * Keycloak Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDto } from './role-dto.model';


export interface GroupDto { 
    id?: string;
    name: string;
    path?: string;
    subGroups: Array<GroupDto>;
    realmRoles: Array<RoleDto>;
}

