/**
 * Keycloak Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDto } from './role-dto.model';
import { ClientRoleDto } from './client-role-dto.model';


export interface RoleAssignmentDto { 
    realmRoles: Array<RoleDto>;
    clientRoles: Array<ClientRoleDto>;
    allRoleIds: Array<string>;
}

